backend:
  image: java:8
  ports:
  - "8080:8080"
  volumes:
  - ./target/aedes.jar:/opt/aedes.jar

  command: java -jar /opt/aedes.jar

  environment:
    AEDES_CONFIG_PATH: classpath:/application.properties

frontend:
  image: nginx
  links: backend
  ports:
  - "8081:80"
  volumes:
   - ./default.config:/etc/nginx/conf.d/default.config