server:
  image: java:8
  ports:
    - "8080:8080"
  volumes:
    - ./server/target/aedes.jar:/opt/aedes.jar

  command: java -jar /opt/aedes.jar

  environment:
    AEDES_CONFIG_PATH: classpath:/application.properties

web:
  image: nginx
  links:
    - server
  ports:
    - "8081:80"
  volumes:
    - ./web/builds/release:/usr/share/nginx/html
    - ./default.config:/etc/nginx/conf.d/default.config
  command: /bin/bash -c "nginx -g 'daemon off;'"