server:
  image: aedes
  ports:
    - "8080:8080"
  command: java -jar /opt/aedes.jar


web:
  image:
  links:
    - server
  ports:
    - "8081:80"
  volumes:
    - ./web/builds/release:/usr/share/nginx/html
    - ./default.config:/etc/nginx/conf.d/default.config
  command: /bin/bash -c "nginx -g 'daemon off;'"
