api:
  image: guihguigo/aedes-server:master-1.0.90
  ports:
    - "8991:8080"
  command: java -jar /opt/aedes.jar

web:
  image: guihguigo/aedes-web:master-1.0.90
  links:
    - api
  ports:
    - "80:80"
  volumes:
  - ./nginx/front:/usr/share/nginx/html
  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  command: /bin/bash -c "nginx -g 'daemon off;'"

