server:
  image: aedes-server
  ports:
    - "8991:8080"
  command: java -jar /opt/aedes.jar

web:
  image: aedes-web
  links:
    - server
  ports:
    - "8080:80"
  volumes:
    - ./web/builds/release:/usr/share/nginx/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  command: /bin/bash -c "nginx -g 'daemon off;'"
