api:
  image: java:8
  ports:
    - "9001:8080"
  volumes:
    - ./server/target/aedes.jar:/opt/aedes.jar
    - /images:/images
  command: java -jar /opt/aedes.jar
  env:
web:
  image: nginx
  links:
    - api
  ports:
    - "80:80"
  volumes:
    - ./web/builds/release:/usr/share/nginx/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  command: /bin/bash -c "nginx -g 'daemon off;'"

